version: '2'
services:
  moveit-service:
    image: gramaziokohler/ros-noetic-dfab
    container_name: moveit-service
    environment:
      - ROS_HOSTNAME=moveit-service
      - ROS_MASTER_URI=http://ros-core:11311
      # GUI: To forward the GUI to an external X11 server (eg. XMing), uncomment the following line
      # - DISPLAY=host.docker.internal:0.0
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      # To change the robot, select the corresponding package name here, eg. `ur10e_moveit_config`
      - ur3e_moveit_config
      - demo.launch
      # To launch the RVIZ GUI, change the following to true
      - use_rviz:=false

  ros-core:
    image: gramaziokohler/ros-noetic-dfab
    container_name: ros-core
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-noetic-dfab
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-noetic-dfab
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-core:11311
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch
